name: "PR Title Checker"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-and-comment:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from PR (Safe Checkout)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Validate PR title
        uses: thehanimo/pr-title-checker@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          remote_configuration_path: "https://raw.githubusercontent.com/leoviana00/GitContributionOpenSource/main/.github/pr-title-checker-config.json"

      # - name: Comment PR on Success 
      #   if: success()
      #   run: |
      #     AUTHOR_NAME="${{ github.event.pull_request.user.login }}"
      #     TITLE_PR=${{ github.event.pull_request.title }}
      #     cat <<EOT > message.txt
      #     A√≠ sim hein $AUTHOR_NAME ! O t√≠tulo do seu PR $TITLE_PR est√° de acordo com o padr√£o!!! ü•≥ 
      #     Vamos realizar a valida√ß√£o do arquivo modificado.
      #     EOT
      #     gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate PR Changed files
        run: |
          AUTHOR_NAME="${{ github.event.pull_request.user.login }}"
          FILE_PATH="contribution_project.md"
          
          # Obt√©m a lista de arquivos modificados usando a CLI do GitHub
          files_changed=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files --paginate | jq -r '.[].filename')
      
          # Lista os arquivos modificados para fins de depura√ß√£o
          echo "Changed files:"
          echo "$files_changed"
          
          # Conta quantos arquivos foram modificados
          NUM_CHANGED_FILES=$(echo "$files_changed" | wc -l)
          
          # Verifica se apenas o arquivo esperado foi modificado
          if [[ "$NUM_CHANGED_FILES" -eq 1 && "$files_changed" == "$FILE_PATH" ]]; then
              echo "PR √© v√°lido, apenas o arquivo esperado foi alterado."
          else
              echo "ERRO: PR inv√°lido. Mais arquivos ou arquivos diferentes do esperado foram alterados."
              exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR on Success and Add Label [automerge]
        if: success()
        run: |
          AUTHOR_NAME=${{ github.event.pull_request.user.login }}
          TITLE_PR=${{ github.event.pull_request.title }}
          REPO_URL=${{ github.event.pull_request.head.repo.html_url }}
          cat <<EOT > message.txt
          A√≠ sim hein $AUTHOR_NAME ! Seu PR foi aprovado ü•≥ 
          Faremos o merge aqui em breve. Muito obrigado pela contribui√ß√£o üöÄ
          EOT

          gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
          gh pr edit ${{ github.event.pull_request.number }} --add-label "automerge"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR on Failure
        if: failure()
        run: |
          AUTHOR_NAME=${{ github.event.pull_request.user.login }}
          cat <<EOT > message.txt
          Ol√° $AUTHOR_NAME ! Parece que houve um problema com o seu PR üßê Aqui est√£o algumas coisas para verificar:
          - Seu PR deve seguir a conven√ß√£o de commits.

          Para obter mais detalhes e garantir que tudo esteja correto, confira nossas instru√ß√µes nos arquivos [Guia do Contribuidor](https://github.com/leoviana00/GitTemplate/blob/main/CONTRIBUTING.md) (que, em geral, N√ÉO devem ser modificados, pois s√£o arquivos gen√©ricos de apoio).

          Se o seu PR tem um objetivo diferente, n√£o se preocupe! Ele ser√° analisado manualmente por nossa equipe, o que pode levar um pouco mais de tempo. Pedimos paci√™ncia nesse processo üôè

          Agradecemos sua contribui√ß√£o e compreens√£o üëäüòâ
          EOT

          gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
  automerge:
    runs-on: ubuntu-latest
    needs: validate-and-comment
    permissions:
      contents: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"